# Generated by Django 5.0.4 on 2024-05-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='picture',
            field=models.ImageField(blank=True, default='media/user.png', null=True, upload_to='media'),
        ),
    ]
