# Generated by Django 5.0.4 on 2024-05-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGine', '0004_alter_blockpost_datetime_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpost',
            name='good_post',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='commentpost',
            name='good_comment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
