# Generated by Django 5.0.4 on 2024-06-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGine', '0005_blockpost_good_post_commentpost_good_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpost',
            name='picture_post',
            field=models.ImageField(blank=True, null=True, upload_to='media_post'),
        ),
        migrations.AddField(
            model_name='commentpost',
            name='picture_comment',
            field=models.ImageField(blank=True, null=True, upload_to='media_comment'),
        ),
    ]
